### ISSUE TITLE
REQ: Expose authorized_keys directly

### ISSUE THREAD

**Issue by deurk** [AnotherStranger/docker-borg-backup#35]
Hello, thank you for building this docker image for borgbackup.

I have a request for you.

When many clients are backing up to a single borg server, the solution of having all the public keys in a variable become quite cumbersome. Also, it is not possible to specify specific repositories access per client with this ENV setup.

Could you please allow exposing `authorized_keys` directly so that it can be directly edited, allowing for more granularity?

Thanks a lot :)

**Comment by AnotherStranger** [comment]
Thank you for your suggestion!

I have to admit that the ENV-Var is not optimal in these cases.
When I have some time at hand, I will have a look at this.

**Comment by AnotherStranger** [comment]
Hey there,
You can try the new feature using the `ghcr.io/anotherstranger/borg-server:feature-alternative-pubkey-management`.
You only have to mount your `authorized_keys` file to `/home/borg/.ssh/authorized_keys`.

Do **not** set the public keys environment variable! Otherwise, the contents of your authorized_keys file will be overwritten.

I will wait for your feedback. ;-)
